[tool.poetry]
name = "django-warrant"
version = "0.2.0"
description = ""
authors = ["Collin Caram <collin@nubrakes.com>"]
readme = "README.md"
packages = [{include = "django_warrant"}]

[tool.poetry.dependencies]
python = ">=3.7,<4"
Django = ">=3.2"
django-braces = "1.11.0"
django-crispy-forms = "1.14.0"
django-extensions = "1.7.7"
django-utils-six = "2.0"
pycognito = "2022.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
